apiVersion: apps/v1
kind: Deployment
metadata:
  name: fecha-hora-k8s-backend
  namespace: fecha-hora-k8s
spec:
  replicas: 1
  selector:
    matchLabels: {app: fecha-hora-k8s-backend}
  template:
    metadata:
      labels: {app: fecha-hora-k8s-backend}
    spec:
      containers:
        - name: fecha-hora-k8s-backend
          image: localhost:5000/fecha-hora-k8s-backend:latest
          imagePullPolicy: Always
          env:
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: postgres-secret, key: POSTGRES_USER}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: postgres-secret, key: POSTGRES_PASSWORD}}
          ports: [{containerPort: 8080}]
---
apiVersion: v1
kind: Service
metadata:
  name: fecha-hora-k8s-backend
  namespace: fecha-hora-k8s
spec:
  selector: {app: fecha-hora-k8s-backend}
  ports: [{port: 8080, targetPort: 8080}]