apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fecha-hora-k8s
type: Opaque
stringData:
  POSTGRES_USER: poc_user
  POSTGRES_PASSWORD: poc_pass
  POSTGRES_DB: fecha-hora-k8s-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fecha-hora-k8s
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fecha-hora-k8s
spec:
  replicas: 1
  selector:
    matchLabels: {app: postgres}
  template:
    metadata:
      labels: {app: postgres}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef: {name: postgres-secret}
          ports: [{containerPort: 5432}]
          volumeMounts:
            - {name: data, mountPath: /var/lib/postgresql/data}
      volumes:
        - name: data
          persistentVolumeClaim: {claimName: postgres-pvc}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fecha-hora-k8s
spec:
  selector: {app: postgres}
  ports: [{port: 5432}]